---
- name: Restore BMC Control-M Alerts to ServiceNow
  ansible.builtin.uri:
    url: "{{ controlm_api_url }}"
    method: POST
    body_format: json
    body:
      destination: "servicenow"
    headers:
      Content-Type: "application/json"
